-- 1. D'abord, on recrée la table avec la bonne structure
DROP TABLE IF EXISTS public.produits;

CREATE TABLE public.produits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    designation TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    description TEXT,
    expiration_date TIMESTAMP WITH TIME ZONE
);

-- 2. Configurer les politiques
ALTER TABLE public.produits ENABLE ROW LEVEL SECURITY;

-- 3. Créer les nouvelles politiques
CREATE POLICY "produits_select_policy" ON public.produits
    FOR SELECT 
    TO public
    USING (true);

CREATE POLICY "produits_insert_policy" ON public.produits
    FOR INSERT 
    TO public
    WITH CHECK (true);

CREATE POLICY "produits_update_policy" ON public.produits
    FOR UPDATE 
    TO public
    USING (true)
    WITH CHECK (true);

CREATE POLICY "produits_delete_policy" ON public.produits
    FOR DELETE 
    TO public
    USING (true);

-- 4. Donner les permissions de base
GRANT ALL ON public.produits TO public;
GRANT ALL ON public.produits TO anon;
